# Generated by setup.py for PyBurst on 2015-02-09 22:46:35 +0000.

version = 'b20401'
date = '2015-02-09 18:45:53 +0000'
release = False

git_hash = 'b2040137542a0707ad894d58522e0bb07c320eeb'
git_branch = 'master'
git_tag = 'None'
git_author = 'Chris Pankow <chris.pankow@ligo.org>'
git_committer = 'Chris Pankow <chris.pankow@ligo.org>'
git_status = 'UNCLEAN: Modified working tree'
git_builder = 'Chris Pankow <chris.pankow@ligo.org>'
git_build_date = '2015-02-09 22:46:35 +0000'
git_verbose_msg = """Branch: master
Tag: None
Id: b2040137542a0707ad894d58522e0bb07c320eeb
Builder: Chris Pankow <chris.pankow@ligo.org>
Build date: 2015-02-09 22:46:35 +0000
Repository status is UNCLEAN: Modified working tree"""